CREATE TABLE RECIPE_CATEGORY
(
  ID   IDENTITY PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL
);

CREATE TABLE RECIPE
(
  ID                 IDENTITY PRIMARY KEY,
  TITLE              VARCHAR(255) NOT NULL,
  DESCRIPTION        VARCHAR(255),
  SERVINGS           INTEGER,
  RECIPE_CATEGORY_ID INTEGER,
  FOREIGN KEY (RECIPE_CATEGORY_ID) REFERENCES RECIPE_CATEGORY (ID)
);

